AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance 

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow SSH 
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: aish-croma-oh
      ImageId: ami-0169aa51f6faf20d5 # Amazon Linux 2 (us-east-1, update if needed)
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: 9.30am-ec2

