AWSTemplateFormatVersion: '2010-09-09'
Description: Create IAM Role

Resources:
  MyExampleRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyExampleRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com  # Change as needed (e.g., lambda.amazonaws.com)
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: MyExamplePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                  - ec2:Describe*
                Resource: "*"
